language: node_js
node_js:
- '10'
before_install:
- npm install
script:
- npm run lint
- npm run test
before_deploy:
- npm run build
deploy:
  provider: npm
  email: sdks@belvo.co
  api_key:
    secure: lz7t0saMyYKFUke5qcH1zMpbzOajD6C4D3lmAdTDt9HRjqDj5jihvYe3AY0FlCB+hKE2eRH0OY2HygqLACoDqtw9eXJE7CHrjkldBp1yvI5vD8ATlq/alrXvBeFw8lSLlLTq0YSQ8kAiaRnq4KNzhsatzcIjoYtiv4FeHhJgU1IR50Gqu19Zlg7JmGPARocanJJa9PVIS2kYZVd7RHsSfkmJKOu6N40Wv5jRCh4Ih+EjyzwTI/CiFs/8O7/c/1STKD6XzUInnJTAUm7tD6l0TPjwEB98EJrXc71LgrJrhDI7jbCbA6TAXb5Q3GK5IBKqiH7O3hS6XYJaXextj8fmWES5Jn5lQt7+oOKoU1GWmsDqcjHwI5RdnVaI8aTVq5AwaN525PRD002r3spDmheuPHzJjvQUh9Pox2eX2hES/FQ4wal6LXNB+HDAaPsLPJAnm5M9A8pvswtP4SUfzkrX77LdXElroJr6eZILkwZhRzpaIcqe01VQ6P/ojIc1wBBLEHvDIuz5z5FRo22MLFkKXUH8dRyrASOfjcS2a3qeQkR3ssXfCJoP05doD/3djiGJs9ES1GdMPFFCm294RMJpfiIGJSOWzTRj++GYPR8IWP2u2jX3B5ZaMP8B84ASeDropnSuDamcRlj9jCMwvqfilF6qfeGdEfMCU9d3EJG+d+A=
  on:
    tags: true
    repo: belvo-finance/belvo-js
  skip_cleanup: true
