export default TaxReturn;
export type Response = import("../types/apiResponses").taxReturnsResponse;
/**
 * @typedef { import("../types/apiResponses").taxReturnsResponse } Response
 */
/**
 * Retrieve tax returns information from a specific fiscal link.
 * @extends Resource<Response>
 */
declare class TaxReturn extends Resource<import("../types/apiResponses").taxReturnsResponse> {
    /**
   * @constant {string}
   * @static
   * */
    static YEARLY: string;
    /**
     * @constant {string}
     * @static
     */
    static MONTHLY: string;
    constructor(session: any);
    /**
     * Retrieve tax returns information from a specific fiscal link.
     *
     * @async
     * @param {string} link - UUID4 representation of a `link` Id.
     * @param {string} yearFrom - Required year from, format is `YYYY-MM-DD`
     * @param {string} yearTo - Required year to, format is `YYYY-MM-DD`.
     * @param {object} [options] - Optional parameters (`token`, `saveData`, `attachPDF`)
     * @param {string} [options.token] - The OTP token generated by the bank.
     * @param {boolean} [options.saveData] - Indicates whether or not to persist the data in Belvo.
     * @param {boolean} [options.attachPDF] - If `true`, you will receive the PDF as a binary string.
     * @param {string} [options.type] - It can be `yearly` (default) or `monthly`
     * @returns {Promise<Response>} Response
     * @throws {RequestError}
     */
    retrieve(link: string, yearDateFrom: any, yearDateTo: any, options?: {
        token?: string;
        saveData?: boolean;
        attachPDF?: boolean;
        type?: string;
    }): Promise<Response>;
    #private;
}
import Resource from "./resources";
