export default Transaction;
/**
 * A Transaction contains the detailed information of each movement inside an Account.
 */
export type Response = import("../types/apiResponses").transactionsResponse;
/**
 * A Transaction contains the detailed information of each movement inside an Account.
 * @typedef { import("../types/apiResponses").transactionsResponse } Response
 * @extends Resource<Response>
 */
declare class Transaction extends Resource<import("../types/apiResponses").transactionsResponse> {
    constructor(session: any);
    /**
     * Retrieve transactions from a specific account or all accounts from a specific link.
     * @async
     * @param {string} link - UUID4 representation of a Link Id.
     * @param {string} dateFrom - Required date from, format is YYYY-MM-DD.
     * @param {object} [options] - Optional parameters (dateTo, token, saveData)
     * @param {string} [options.dateTo] - The date you want to stop getting transactions for, in YYYY-MM-DD format
     * @param {string} [options.token] - The OTP token generated by the bank.
     * @param {boolean} [options.saveData] - Indicates whether or not to persist the data in Belvo. When set to false, the data won't be persisted.
     * @returns {Promise<Response>} Response
     * @throws {RequestError}
     */
    retrieve(link: string, dateFrom: string, options?: {
        dateTo?: string;
        token?: string;
        saveData?: boolean;
    }): Promise<Response>;
    #private;
}
import Resource from "./resources";
