import Resource from './resources';

/**
 * @typedef { import("../types/apiResponses").accountsResponse } Response
 */

/**
 * An Account is the representation of a bank account inside a financial institution.
 * @extends Resource<Response>
 */
class Account extends Resource {
  #endpoint = 'api/accounts/'

  /**
   * Retrieve accounts from an existing link.
   * @async
   * @param {string} link UUID4 representation of a Link Id.
   * @param {object} [options] - Optional parameters (token, saveData)
   * @param {string} [options.token] - The OTP token generated by the bank.
   * @param {boolean} [options.saveData] - Indicates whether or not to persist the data in Belvo.
   * @returns {Promise<Response>} Response
   * @throws {RequestError}
   */
  async retrieve(link, options = {}) {
    const { token, encryptionKey, saveData } = options;
    const result = await this.session.post(this.#endpoint, {
      link,
      token,
      encryption_key: encryptionKey,
      save_data: saveData,
    });
    return result;
  }
}

export default Account;
