import moment from 'moment';
import Resource from './resources';

/**
 * @typedef { import("../types/apiResponses").balancesResponse } Response
 */

/**
 * A Balance represents the financial status of an Account at a given time.
 * @extends Resource<Response>
 */
class Balance extends Resource {
  #endpoint = 'api/balances/'

  /**
   * Retrieve balances from a specific account or all accounts from a specific link.
   * @async
   * @param {string} link - UUID4 representation of a link Id.
   * @param {string} dateFrom - Required date from, format is YYYY-MM-DD
   * @param {object} [options] - Optional parameters (account, dateTo, token, saveData)
   * @param {string} [options.token] - The OTP token generated by the bank.
   * @param {string|null} [options.account] - If provided, only balances matching this account.id are returned.
   * @param {string} [options.dateTo] - Date that you want to stop receiving balances, in YYYY-MM-DD format.
   * @param {boolean} [options.saveData] - Indicates whether or not to persist the data in Belvo. When set to false, the data won't be persisted.
   * @returns {Promise<Response>} Response
   * @throws {RequestError}
   */
  async retrieve(link, dateFrom, options = {}) {
    const {
      account, token, encryptionKey, saveData,
    } = options;
    let {
      dateTo,
    } = options;
    if (!dateTo) {
      dateTo = moment().format('YYYY-MM-DD');
    }
    const result = await this.session.post(this.#endpoint, {
      link,
      token,
      account,
      date_from: dateFrom,
      date_to: dateTo,
      encryption_key: encryptionKey,
      save_data: saveData,
    });
    return result;
  }
}

export default Balance;
