import Resource from './resources';
import { encodeFileB64 } from './utils';

/**
 * @typedef { import("../types/apiResponses").linksResponse } Response
 */

/**
 * A Link is a set of credentials associated to a end-user access to an Institution.
 * @extends Resource<Response>
 * */

class Link extends Resource {
  /**
   * Links endpoint.
   * @private
   */
  #endpoint = 'api/links/';

  /**
   * @constant {string}
   * @static
   * */
  static SINGLE = 'single';

  /**
   * @constant {string}
   * @static
   */
  static RECURRENT = 'recurrent';

  /**
   * Register a new link.
   * @async
   * @param {string} institution - Institution's code.
   * @param {string} username - Username used to sign in online by the end-user.
   * @param {string} password - Password used to sign in online by the end-user.
   * @param {object} [options] - Optional parameters
   *   (`token`, `usernameType`, `username2`, `username3`, `password2`, `accessMode`,
   *    `certificate`, `privateKey`, `externalId`).
   * @param {string} [options.token] - The OTP token generated by the bank to log in.
   * @param {string} [options.usernameType] - Type of document to be used as a username.
   * @param {string} [options.username2] - The second username used to log in to the institution.
   * @param {string} [options.username3] - The third username used to log in to the institution.
   * @param {string} [options.password2] - The second password used to log in to the institution.
   * @param {string} [options.accessMode] - The type of link to create.
   * @param {string} [options.certificate] - Certificate provided from certain fiscal institutions.
   * @param {string} [options.privateKey] - Private Key provided from certain fiscal institutions.
   * @param {string} [options.externalId] - An additional identifier for the link id.
   * @returns {Promise<Response>} Newly created link.
   * @throws {RequestError}
   */
  async register(
    institution, username, password, options = {},
  ) {
    const {
      token, usernameType, username2, username3, password2, accessMode, externalId,
    } = options;
    let {
      certificate, privateKey,
    } = options;
    certificate = certificate ? encodeFileB64(certificate) : certificate;
    privateKey = privateKey ? encodeFileB64(privateKey) : privateKey;
    const result = await this.session.post(
      this.#endpoint, {
        institution,
        username,
        username2,
        username3,
        password,
        password2,
        token,
        access_mode: accessMode,
        username_type: usernameType,
        certificate,
        private_key: privateKey,
        external_id: externalId,
      },
    );
    return result;
  }

  /**
   * Update link's password and password2.
   * Use this function when you want to update the link credentials.
   * Only updating passwords is available.
   * @async
   * @param {string} id - UUID4 representation of the link Id.
   * @param {string} password - New password.
   * @param {object} options - Optional parameters
   *  (token, password2, usernameType, certificate, privateKey).
   * @param {string} [options.token] - The OTP token generated by the bank to log in.
   * @param {string} [options.usernameType] - Type of document to be used as a username.
   * @param {string} [options.password2] - The second password used to log in to the institution.
   * @param {string} [options.certificate] - Certificate provided from certain fiscal institutions.
   * @param {string} [options.privateKey] - Private Key provided from certain fiscal institutions.
   * @returns {Promise<Response>} Response
   * @throws {RequestError}
   */
  async update(id, options = {}) {
    const {
      token, password, password2, usernameType,
    } = options;
    let {
      certificate, privateKey,
    } = options;
    certificate = certificate ? encodeFileB64(certificate) : certificate;
    privateKey = privateKey ? encodeFileB64(privateKey) : privateKey;
    const result = await this.session.put(this.#endpoint, id, {
      password,
      password2,
      token,
      username_type: usernameType,
      certificate,
      private_key: privateKey,
    });
    return result;
  }

  /**
   * Request scoped tokens to operate with a single link
   * @async
   * @param {string} id - UUID4 representation of the link Id.
   * @param {string} scopes - List of comma separated scopes
   * @returns {Promise<object>} Response
   * @throws {RequestError}
   */
  async token(id, scopes) {
    return this.session.post('api/token/', { link_id: id, scopes });
  }
}

export default Link;
