import Resource from './resources';

/**
 * An Owner represents the person who has access to a Link and
 * is the owner of all the Accounts inside the Link.
 * @typedef { import("../types/apiResponses").ownersResponse } Response
 * @extends Resource<Response>
 */
class Owner extends Resource {
  #endpoint = 'api/owners/'

  /**
   * Retrieve owner information from a specific link.
   * @async
   * @param {string} link - UUID4 representation of a link Id.
   * @param {object} [options] - Optional parameters (`token`, `saveData`)
   * @param {string} [options.token] - The OTP token generated by the bank.
   * @param {boolean} [options.saveData] - Indicates whether or not to persist the data in Belvo. When set to `false`, the data won't be persisted.
   * @returns {Promise<Response>} Response
   * @throws {RequestError}
   */
  async retrieve(link, options = {}) {
    const { token, encryptionKey, saveData } = options;
    const result = await this.session.post(this.#endpoint, {
      link,
      token,
      encryption_key: encryptionKey,
      save_data: saveData,
    });
    return result;
  }
}

export default Owner;
