import moment from 'moment';
import Resource from './resources';

/**
 * A Transaction contains the detailed information of each movement inside an Account.
 * @typedef { import("../types/apiResponses").transactionsResponse } Response
 * @extends Resource<Response>
 */

class Transaction extends Resource {
  #endpoint = 'api/transactions/'

  /**
   * Retrieve transactions from a specific account or all accounts from a specific link.
   * @async
   * @param {string} link - UUID4 representation of a Link Id.
   * @param {string} dateFrom - Required date from, format is YYYY-MM-DD.
   * @param {object} [options] - Optional parameters (dateTo, token, saveData)
   * @param {string} [options.dateTo] - The date you want to stop getting transactions for, in YYYY-MM-DD format
   * @param {string} [options.token] - The OTP token generated by the bank.
   * @param {boolean} [options.saveData] - Indicates whether or not to persist the data in Belvo. When set to false, the data won't be persisted.
   * @returns {Promise<Response>} Response
   * @throws {RequestError}
   */
  async retrieve(link, dateFrom, options = {}) {
    const {
      token, encryptionKey, saveData,
    } = options;
    let {
      dateTo,
    } = options;
    if (!dateTo) {
      dateTo = moment().format('YYYY-MM-DD');
    }
    const result = await this.session.post(this.#endpoint, {
      link,
      token,
      date_from: dateFrom,
      date_to: dateTo,
      encryption_key: encryptionKey,
      save_data: saveData,
    });
    return result;
  }
}

export default Transaction;
